install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module PsScriptAnalyzer -Force
build: off
test_script:
  - ps: |
      $testName = "PSScriptAnalyzer"
      Add-AppveyorTest -Name $testName -Outcome Running
      $result = Invoke-ScriptAnalyzer -Path $pwd -Recurse | Out-String
      if ($result.Length -gt 0) {
        $result
        Update-AppveyorTest -Name $testName -Outcome Failed -ErrorMessage $result
        Throw $testName + ' failed'
      } else {        
        Update-AppveyorTest -Name $testName -Outcome Passed
      }      
