image: Visual Studio 2017
install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module -Name PsScriptAnalyzer -Force
  - ps: Install-Module -Name Pester -Force
build: off
build_script:
  - docker version
  - docker images
test_script:
  - ps: Invoke-Pester