image: Visual Studio 2017
install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module -Name PsScriptAnalyzer -Force
  - ps: Install-Module -Name Pester -Force -SkipPublisherCheck
build: off
build_script:
  - docker version
  - docker images
test_script:
  - ps: |
      $results = ".\TestResults.xml"
      $url = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
      Invoke-Pester -OutputFormat NUnitXml -OutputFile $results
      $path = Resolve-Path $results
      Write-Host 'Uploading Pester test results from ' + $path + ' to ' + $url
      (New-Object 'System.Net.WebClient').UploadFile($url, $path)
