image: Visual Studio 2017
install:
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Module -Name PsScriptAnalyzer -Force
  - ps: Install-Module -Name Pester -Force -SkipPublisherCheck
build: off
build_script:
  - ps: Write-Host "APPVEYOR_JOB_ID is $env:APPVERYOR_JOB_ID"
  - docker version
  - docker images
test_script:
  - ps: |
      $results = "TestResults.xml"
      $uploadUrl = "https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)"
      Invoke-Pester -OutputFormat NUnitXml -OutputFile $results
      (New-Object 'System.Net.WebClient').UploadFile($uploadUrl, $results)
